[theme]
primaryColor="#000000"                # Accent color (buttons, sliders, etc.)
backgroundColor="#000000"             # Main background (pure white)
secondaryBackgroundColor="#3a3a3a"    # Sidebar / widgets background (light gray)
textColor="#FFFFFF"                    # Black text
font="serif"                      # Clean readable font
